# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c6f8b1ce0966cd804ee2d21ea133fb53e7bc11b973c20f90c21aa1a7bdb5bf722fd283540059e8a8919a53b2f95905db6f1572c00c4f6a0ec0db3d60f37706

test:
  secret_key_base: 50a6277bfc44072457d911dd9988c6b50acf4915fcaafa3b8aa17125d06d6f449b0061c50246d4f5adb2b053c778f740772fd2fdd5316fa98a662a9e3291c17b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
